### ISSUE TITLE
running gophish as a service, it doesnt show credentials

### ISSUE THREAD

**Issue by sbjoy2019** [gophish/user-guide#1]
![Gophish snip](https://user-images.githubusercontent.com/49207098/55424413-e3f66600-5588-11e9-9b93-c7f36f6cfb18.PNG)
I don't know what I am doing wrong.Gophish wont show phished credentials, only shows email opened and link clicked

**Comment by jordan-wright** [comment]
Hi there!

If you're still having issues with this, please [file an issue](https://github.com/gophish/gophish/issues/new) over at the main Gophish repository.

Thanks!
