### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by bubaiwantong** [gophish/user-guide#2]
Hello:
    when i run ./gophish start system, show below:

time="2019-04-17T14:23:44+08:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-04-17T14:23:44+08:00" level=warning msg="No contact address has been configured."
time="2019-04-17T14:23:44+08:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2019-04-17T14:23:44+08:00" level=error msg="no valid version found"
time="2019-04-17T14:23:44+08:00" level=fatal msg="no valid version found"

**Comment by jordan-wright** [comment]
Hi there!

If you're still having issues with this, please [file an issue](https://github.com/gophish/gophish/issues/new) over at the main Gophish repository.

Thanks!
